# Generated by Django 5.2.8 on 2026-01-12 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_blog_date_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BrandingSettings',
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 12, 14, 3, 43, 310454)),
        ),
    ]
