# Generated by Django 5.2.8 on 2026-01-12 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_applicationbrandingsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 12, 18, 43, 6, 811929)),
        ),
    ]
