# Generated by Django 5.2.8 on 2026-01-13 10:45

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_alter_salesettings_default_tax'),
        ('core', '0004_alter_blog_date_created'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 13, 13, 45, 56, 578307)),
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(help_text='Source currency code (ISO 4217)', max_length=3)),
                ('to_currency', models.CharField(help_text='Target currency code (ISO 4217)', max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, help_text='Exchange rate (1 from_currency = rate to_currency)', max_digits=18)),
                ('effective_date', models.DateField(help_text='Date from which this rate is effective')),
                ('source', models.CharField(choices=[('manual', 'Manual Entry'), ('api', 'Exchange Rate API'), ('bank', 'Bank Rate')], default='manual', help_text='Source of the exchange rate', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(blank=True, help_text='Business-specific rate (null = system-wide)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rates', to='business.bussiness')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exchange_rates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exchange Rate',
                'verbose_name_plural': 'Exchange Rates',
                'ordering': ['-effective_date', '-created_at'],
                'indexes': [models.Index(fields=['from_currency', 'to_currency'], name='core_exchan_from_cu_4e4bb6_idx'), models.Index(fields=['effective_date'], name='core_exchan_effecti_c82142_idx'), models.Index(fields=['is_active'], name='core_exchan_is_acti_de3b34_idx')],
                'unique_together': {('from_currency', 'to_currency', 'effective_date', 'business')},
            },
        ),
    ]
