# Generated by Django 5.2.8 on 2026-01-14 19:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_blog_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 14, 22, 31, 10, 732631)),
        ),
    ]
