# Generated by Django 5.2.8 on 2026-01-15 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_blog_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 15, 13, 46, 27, 451625)),
        ),
    ]
