# Generated by Django 5.2.8 on 2026-01-14 19:31

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
        ('business', '0003_alter_salesettings_default_tax'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentaccounts',
            options={'verbose_name': 'Payment Account', 'verbose_name_plural': 'Payment Accounts'},
        ),
        migrations.AddField(
            model_name='paymentaccounts',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current account balance', max_digits=14),
        ),
        migrations.AddField(
            model_name='paymentaccounts',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_accounts', to='business.bussiness'),
        ),
        migrations.AlterField(
            model_name='paymentaccounts',
            name='branch',
            field=models.CharField(blank=True, help_text='Bank branch name (e.g., Main St Branch)', max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='paymentaccounts',
            index=models.Index(fields=['business'], name='idx_payment_accts_business'),
        ),
    ]
