# Generated by Django 5.2.8 on 2026-01-16 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backup',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='backup',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='backup',
            name='storage_type',
            field=models.CharField(choices=[('local', 'Local Storage'), ('s3', 'Amazon S3')], default='local', max_length=10),
        ),
        migrations.AlterField(
            model_name='backup',
            name='path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='backup',
            name='size',
            field=models.BigIntegerField(default=0, help_text='Size in bytes'),
        ),
    ]
