# Generated by Django 5.2.8 on 2026-02-03 12:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authmanagement', '0002_alter_backup_options_backup_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='signature',
            field=models.ImageField(blank=True, help_text='Upload your digital signature image (transparent PNG recommended, max 500x200px). Used for signing approved documents.', null=True, upload_to='user_signatures'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, default='+254700000000', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (e.g., +254700000000 or +14155552671)', regex='^\\+?[1-9]\\d{1,14}$')]),
        ),
    ]
