# Generated by Django 5.2.8 on 2026-01-12 15:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_orders', '0003_add_tax_mode_tax_rate'),
        ('invoicing', '0002_initial'),
        ('orders', '0002_initial'),
        ('quotations', '0002_quotation_rfq_number_quotation_tender_quotation_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('baseorder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core_orders.baseorder')),
                ('delivery_note_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('delivery_date', models.DateField(default=django.utils.timezone.now)),
                ('delivery_address', models.TextField(blank=True, help_text='Delivery address')),
                ('driver_name', models.CharField(blank=True, help_text='Driver/courier name', max_length=100)),
                ('driver_phone', models.CharField(blank=True, help_text='Driver contact number', max_length=20)),
                ('vehicle_number', models.CharField(blank=True, help_text='Vehicle registration number', max_length=50)),
                ('received_by', models.CharField(blank=True, help_text='Name of person who received goods', max_length=100)),
                ('received_at', models.DateTimeField(blank=True, help_text='When goods were received', null=True)),
                ('receiver_signature', models.ImageField(blank=True, null=True, upload_to='delivery_signatures/')),
                ('special_instructions', models.TextField(blank=True, help_text='Special delivery instructions')),
                ('source_invoice', models.ForeignKey(blank=True, help_text='Source invoice for this delivery note', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dn_from_invoice', to='invoicing.invoice')),
                ('source_purchase_order', models.ForeignKey(blank=True, help_text='Source purchase order for this delivery note', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dn_from_po', to='orders.purchaseorder')),
            ],
            options={
                'verbose_name': 'Delivery Note',
                'verbose_name_plural': 'Delivery Notes',
                'ordering': ['-delivery_date', '-created_at'],
                'indexes': [models.Index(fields=['delivery_note_number'], name='idx_delivery_note_number'), models.Index(fields=['source_invoice'], name='idx_dn_src_invoice'), models.Index(fields=['delivery_date'], name='idx_delivery_note_date')],
            },
            bases=('core_orders.baseorder',),
        ),
        migrations.CreateModel(
            name='ProformaInvoice',
            fields=[
                ('baseorder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core_orders.baseorder')),
                ('proforma_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('proforma_date', models.DateField(default=django.utils.timezone.now)),
                ('valid_until', models.DateField(blank=True, help_text='Proforma validity date', null=True)),
                ('customer_notes', models.TextField(blank=True, default='This is a proforma invoice and not a demand for payment.')),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('converted_invoice', models.ForeignKey(blank=True, help_text='Invoice created from this proforma', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_proformas', to='invoicing.invoice')),
                ('source_quotation', models.ForeignKey(blank=True, help_text='Source quotation for this proforma', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proforma_invoices', to='quotations.quotation')),
            ],
            options={
                'verbose_name': 'Proforma Invoice',
                'verbose_name_plural': 'Proforma Invoices',
                'ordering': ['-proforma_date', '-created_at'],
                'indexes': [models.Index(fields=['proforma_number'], name='idx_proforma_number'), models.Index(fields=['proforma_date'], name='idx_proforma_date'), models.Index(fields=['valid_until'], name='idx_proforma_valid_until')],
            },
            bases=('core_orders.baseorder',),
        ),
    ]
