# Generated by Django 5.2.8 on 2026-01-19 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_add_currency_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='payment',
            name='idx_payment_currency',
        ),
    ]
