# Generated by Django 5.2.8 on 2026-01-12 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prefixsettings',
            name='credit_note',
            field=models.CharField(default='CRN', help_text='Credit Note prefix', max_length=5),
        ),
        migrations.AddField(
            model_name='prefixsettings',
            name='debit_note',
            field=models.CharField(default='DBN', help_text='Debit Note prefix', max_length=5),
        ),
        migrations.AddField(
            model_name='prefixsettings',
            name='delivery_note',
            field=models.CharField(default='POD', help_text='Delivery Note (Proof of Delivery) prefix', max_length=5),
        ),
        migrations.AddField(
            model_name='prefixsettings',
            name='invoice',
            field=models.CharField(default='INV', help_text='Invoice prefix', max_length=5),
        ),
        migrations.AddField(
            model_name='prefixsettings',
            name='quotation',
            field=models.CharField(default='QOT', help_text='Quotation prefix', max_length=5),
        ),
        migrations.AddField(
            model_name='prefixsettings',
            name='stock_adjustment',
            field=models.CharField(default='ADJ', help_text='Stock Adjustment prefix', max_length=5),
        ),
        migrations.AlterField(
            model_name='prefixsettings',
            name='business_location',
            field=models.CharField(default='BL', help_text='Business Location prefix', max_length=5),
        ),
        migrations.AlterField(
            model_name='prefixsettings',
            name='expense',
            field=models.CharField(default='EP', help_text='Expense prefix', max_length=5),
        ),
        migrations.AlterField(
            model_name='prefixsettings',
            name='purchase',
            field=models.CharField(default='P', help_text='Purchase prefix', max_length=5),
        ),
        migrations.AlterField(
            model_name='prefixsettings',
            name='purchase_order',
            field=models.CharField(default='LSO', help_text='Purchase Order prefix (Local Sales Order)', max_length=5),
        ),
        migrations.AlterField(
            model_name='prefixsettings',
            name='purchase_requisition',
            field=models.CharField(default='PRQ', help_text='Purchase Requisition prefix', max_length=5),
        ),
        migrations.AlterField(
            model_name='prefixsettings',
            name='purchase_return',
            field=models.CharField(default='PRT', help_text='Purchase Return prefix', max_length=5),
        ),
        migrations.AlterField(
            model_name='prefixsettings',
            name='sale_return',
            field=models.CharField(default='SR', help_text='Sale Return prefix', max_length=5),
        ),
        migrations.AlterField(
            model_name='prefixsettings',
            name='stock_transfer',
            field=models.CharField(default='STR', help_text='Stock Transfer prefix', max_length=5),
        ),
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('invoice', 'Invoice'), ('purchase_order', 'Purchase Order'), ('credit_note', 'Credit Note'), ('debit_note', 'Debit Note'), ('quotation', 'Quotation'), ('delivery_note', 'Delivery Note'), ('expense', 'Expense'), ('stock_transfer', 'Stock Transfer'), ('stock_adjustment', 'Stock Adjustment'), ('purchase_requisition', 'Purchase Requisition'), ('sale_return', 'Sale Return'), ('purchase_return', 'Purchase Return')], help_text='Type of document this sequence tracks', max_length=50)),
                ('current_sequence', models.PositiveIntegerField(default=0, help_text='Current sequence number (last used)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(help_text='Business this sequence belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='document_sequences', to='business.bussiness')),
            ],
            options={
                'verbose_name': 'Document Sequence',
                'verbose_name_plural': 'Document Sequences',
                'db_table': 'document_sequences',
                'indexes': [models.Index(fields=['business', 'document_type'], name='idx_doc_seq_business_type')],
                'unique_together': {('business', 'document_type')},
            },
        ),
    ]
