# Generated by Django 5.2.8 on 2026-01-12 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_document_sequence_and_prefixes'),
        ('taxes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesettings',
            name='default_tax',
            field=models.ForeignKey(blank=True, default=None, help_text='Default tax rate for sales', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_settings', to='taxes.tax'),
        ),
    ]
