# Generated by Django 5.2.8 on 2026-02-03 12:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_alter_salesettings_default_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='bussiness',
            name='business_stamp',
            field=models.ImageField(blank=True, help_text='Upload official business stamp image (transparent PNG recommended, max 300x300px). Appears on invoices, quotations, and official documents.', null=True, upload_to='business/stamps'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='alternate_contact_number',
            field=models.CharField(blank=True, default='+254700000000', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (e.g., +254700000000 or +14155552671)', regex='^\\+?[1-9]\\d{1,14}$')]),
        ),
        migrations.AlterField(
            model_name='branch',
            name='contact_number',
            field=models.CharField(default='+254700000000', max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (e.g., +254700000000 or +14155552671)', regex='^\\+?[1-9]\\d{1,14}$')]),
        ),
        migrations.AlterField(
            model_name='branch',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='WhatsApp business number', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (e.g., +254700000000 or +14155552671)', regex='^\\+?[1-9]\\d{1,14}$')]),
        ),
    ]
