# Generated by Django 5.2.8 on 2026-01-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0002_quotation_rfq_number_quotation_tender_quotation_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='acceptance_notes',
            field=models.TextField(blank=True, help_text='Notes provided when quotation was accepted', null=True),
        ),
        migrations.AddField(
            model_name='quotationemaillog',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes for this log entry', null=True),
        ),
        migrations.AlterField(
            model_name='quotationemaillog',
            name='email_type',
            field=models.CharField(choices=[('sent', 'Quotation Sent'), ('reminder', 'Follow-up Reminder'), ('thank_you', 'Thank You'), ('expired_notice', 'Expiry Notice'), ('accepted', 'Quotation Accepted')], max_length=20),
        ),
        migrations.AlterField(
            model_name='quotationemaillog',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('bounced', 'Bounced'), ('failed', 'Failed'), ('logged', 'Logged')], default='sent', max_length=20),
        ),
    ]
