# Generated by Django 5.2.8 on 2026-01-13 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrations',
            name='integration_type',
            field=models.CharField(choices=[('PAYMENT', 'Payment Integration'), ('NOTIFICATION', 'Notification Integration'), ('OTHER', 'Other Integration')], max_length=20),
        ),
        migrations.CreateModel(
            name='ExchangeRateAPISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('EXCHANGERATE_HOST', 'exchangerate.host'), ('OPEN_EXCHANGE', 'Open Exchange Rates'), ('FIXER', 'Fixer.io'), ('CURRENCY_LAYER', 'Currency Layer'), ('OTHER', 'Other Provider')], default='EXCHANGERATE_HOST', help_text='Exchange rate API provider', max_length=50)),
                ('provider_name', models.CharField(default='exchangerate.host', help_text='Display name for the provider', max_length=255)),
                ('api_endpoint', models.URLField(default='https://api.exchangerate.host/live', help_text='API endpoint URL for fetching rates')),
                ('access_key', models.CharField(blank=True, help_text='API access key (will be encrypted)', max_length=1500, null=True)),
                ('source_currency', models.CharField(default='USD', help_text='Base/source currency for rate queries', max_length=3)),
                ('target_currencies', models.JSONField(default=['KES', 'USD', 'EUR', 'GBP'], help_text="List of target currencies to fetch rates for (e.g., ['KES', 'EUR', 'GBP'])")),
                ('fetch_time', models.TimeField(default=datetime.time(0, 0), help_text='Time of day to fetch exchange rates (24hr format)')),
                ('last_fetch_at', models.DateTimeField(blank=True, help_text='Timestamp of last successful rate fetch', null=True)),
                ('last_fetch_status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', help_text='Status of the last fetch operation', max_length=20)),
                ('last_fetch_error', models.TextField(blank=True, help_text='Error message from last failed fetch', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable automatic rate fetching')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exchange Rate API Settings',
                'verbose_name_plural': 'Exchange Rate API Settings',
                'indexes': [models.Index(fields=['provider'], name='idx_exchange_rate_provider'), models.Index(fields=['is_active'], name='idx_exchange_rate_active')],
            },
        ),
    ]
