# Generated by Django 5.2.8 on 2026-01-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_alter_integrations_integration_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerateapisettings',
            name='target_currencies',
            field=models.JSONField(default=list, help_text="List of target currencies to fetch rates for (e.g., ['KES', 'EUR', 'GBP'])"),
        ),
    ]
