# Generated by Django 5.2.8 on 2026-01-15 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_alter_exchangerateapisettings_target_currencies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrations',
            name='name',
            field=models.CharField(choices=[('MPESA', 'Mpesa'), ('PAYPAL', 'PayPal'), ('CARD', 'Card Payment'), ('PAYSTACK', 'Paystack')], default='MPESA', max_length=100),
        ),
        migrations.CreateModel(
            name='PaystackSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_test_mode', models.BooleanField(default=True, help_text='Use Paystack test environment. Toggle off for production.')),
                ('public_key', models.CharField(default='pk_test_your_paystack_public_key', help_text='Paystack public key (starts with pk_test_ or pk_live_)', max_length=1500)),
                ('secret_key', models.CharField(default='sk_test_your_paystack_secret_key', help_text='Paystack secret key (starts with sk_test_ or sk_live_)', max_length=1500)),
                ('webhook_secret', models.CharField(blank=True, help_text='Webhook signature verification secret', max_length=1500, null=True)),
                ('base_url', models.URLField(default='https://api.paystack.co', help_text='Paystack API base URL')),
                ('webhook_url', models.URLField(default='https://yourdomain.com/api/payments/paystack/webhook', help_text='URL for Paystack webhooks')),
                ('callback_url', models.URLField(default='https://yourdomain.com/payment/callback', help_text='URL to redirect customers after payment')),
                ('enabled_channels', models.JSONField(default=list, help_text='Enabled payment channels: card, bank, bank_transfer, ussd, qr, mobile_money')),
                ('default_currency', models.CharField(default='KES', help_text='Default currency (NGN, GHS, ZAR, KES, USD)', max_length=3)),
                ('business_name', models.CharField(default='BengoERP', help_text='Business name shown on payment pages', max_length=255)),
                ('support_email', models.EmailField(default='support@bengoerp.com', help_text='Support email for customer inquiries', max_length=255)),
                ('subaccount_code', models.CharField(blank=True, help_text='Subaccount code for split payments', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration', models.ForeignKey(blank=True, limit_choices_to={'integration_type': 'PAYMENT'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paystack_settings', to='integrations.integrations')),
            ],
            options={
                'verbose_name': 'Paystack Settings',
                'verbose_name_plural': 'Paystack Settings',
                'indexes': [models.Index(fields=['is_test_mode'], name='idx_paystack_test_mode')],
            },
        ),
    ]
