# Generated by Django 5.2.8 on 2026-01-13 10:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_orders', '0003_add_tax_mode_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseorder',
            name='currency',
            field=models.CharField(choices=[('KES', 'Kenya Shilling (KES)'), ('USD', 'US Dollar (USD)'), ('EUR', 'Euro (EUR)'), ('GBP', 'British Pound (GBP)'), ('UGX', 'Uganda Shilling (UGX)'), ('TZS', 'Tanzania Shilling (TZS)'), ('ZAR', 'South African Rand (ZAR)'), ('NGN', 'Nigerian Naira (NGN)')], default='KES', help_text='Currency for this order (ISO 4217 code)', max_length=3),
        ),
        migrations.AddField(
            model_name='baseorder',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.000000'), help_text='Exchange rate to base currency (KES) at time of order', max_digits=18),
        ),
    ]
