# Generated by Django 5.2.8 on 2026-01-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_orders', '0004_baseorder_currency_baseorder_exchange_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('ordered', 'Ordered'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('received', 'Received'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('on_hold', 'On Hold'), ('backordered', 'Backordered'), ('refund_requested', 'Refund Requested'), ('refunded', 'Refunded'), ('payment_failed', 'Payment Failed')], default='draft', max_length=50),
        ),
    ]
