# Generated by Django 5.2.8 on 2026-01-13 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_alter_sales_date_added_alter_sales_date_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 13, 10, 45, 56, 600040, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 13, 10, 45, 56, 600051, tzinfo=datetime.timezone.utc)),
        ),
    ]
