# Generated by Django 5.2.8 on 2026-01-15 07:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0002_initial'),
        ('core', '0010_alter_blog_date_created'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalstep',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this step is active'),
        ),
        migrations.AddIndex(
            model_name='approvalstep',
            index=models.Index(fields=['is_active'], name='idx_approval_step_active'),
        ),
    ]
