# Generated by Django 5.2.8 on 2026-01-16 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0003_approvalstep_is_active_and_more'),
        ('business', '0003_alter_salesettings_default_tax'),
        ('contacts', '0006_alter_contact_added_on'),
        ('requisitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementrequest',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this requisition is for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_requests', to='business.branch'),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='business',
            field=models.ForeignKey(blank=True, help_text='Business this requisition belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procurement_requests', to='business.bussiness'),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='preferred_suppliers',
            field=models.ManyToManyField(blank=True, help_text='Preferred suppliers for this requisition', related_name='preferred_requisitions', to='contacts.contact'),
        ),
        migrations.AddIndex(
            model_name='procurementrequest',
            index=models.Index(fields=['business'], name='idx_proc_request_business'),
        ),
        migrations.AddIndex(
            model_name='procurementrequest',
            index=models.Index(fields=['branch'], name='idx_proc_request_branch'),
        ),
    ]
