# Generated by Django 5.2.8 on 2026-01-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inappnotification',
            name='read_at',
            field=models.DateTimeField(blank=True, help_text='When the notification was read', null=True),
        ),
    ]
