# Generated by Django 5.2.8 on 2026-01-12 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockinventory', '0001_initial'),
        ('taxes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinventory',
            name='applicable_tax',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_items', to='taxes.tax'),
        ),
    ]
